apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-automation
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  project: default
  source:
    repoURL: https://github.com/maxisses/portfolio-demo.git
    targetRevision: main
    path: gitops/components/fleet-automation
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 20
      backoff:
        duration: 30s
        factor: 1
