apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - acm.yaml
  - cert-manager.yaml
  - connectivity-link.yaml
  - external-secrets.yaml
  - fleet.yaml
  - gpu-operator.yaml
  - leader-worker-set.yaml
  - maas.yaml
  - monitoring.yaml
  - nfd.yaml
  - rhoai.yaml
