apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterset.yaml
  - ocp19.yaml
  - ocp20.yaml
  - policies-base.yaml
  - policy-gitops-edge.yaml
  - policy-console-banner.yaml
  - policy-console-banner-cleanup.yaml
  - policy-edge-version.yaml
  - gitops-pull.yaml
